// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/portifolio/:id?": {
    params: {
      "id"?: string;
    };
  };
  "/trabalhos": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/perfil": {
    params: {};
  };
  "/enter": {
    params: {};
  };
  "/trocarsenha": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/portifolio/:id?" | "/trabalhos" | "/chat" | "/perfil" | "/enter" | "/trocarsenha";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/rotaportifolio.tsx": {
    id: "routes/rotaportifolio";
    page: "/portifolio/:id?";
  };
  "routes/rotatrabalho.tsx": {
    id: "routes/rotatrabalho";
    page: "/trabalhos";
  };
  "routes/rotachat.tsx": {
    id: "routes/rotachat";
    page: "/chat";
  };
  "routes/redirectprofile.tsx": {
    id: "routes/redirectprofile";
    page: "/perfil";
  };
  "routes/redirect.tsx": {
    id: "routes/redirect";
    page: "/enter";
  };
  "routes/redirectsendpassword.tsx": {
    id: "routes/redirectsendpassword";
    page: "/trocarsenha";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/rotaportifolio": typeof import("./app/routes/rotaportifolio.tsx");
  "routes/rotatrabalho": typeof import("./app/routes/rotatrabalho.tsx");
  "routes/rotachat": typeof import("./app/routes/rotachat.tsx");
  "routes/redirectprofile": typeof import("./app/routes/redirectprofile.tsx");
  "routes/redirect": typeof import("./app/routes/redirect.tsx");
  "routes/redirectsendpassword": typeof import("./app/routes/redirectsendpassword.tsx");
};